language: node_js
node_js: stable
branches:
- only: master
install:
- npm install
before_script:
- git config --global user.name "limengke123"
- git config --global user.email "752140235@qq.com"
script:
- hexo clean
- hexo generate
after_script:
- cd ./public
- git init
- git add .
- git commit -m "Travis-CI update docs"
- git push --force https://${TOKEN}@${GH_REF} master:gh-pages
env:
  global:
  - GH_REF: github.com/limengke123/newBlog.git
  - secure: WD0McHXQTMCiQpYV9H8FuwMnYZaQZhSmMSXTWoRvzoYtfd5PxwbLwIA9QQL4afCCcczfyrKubszqeVIK/Q/y/jvGAU0UYeNZXoeDsltyV5W7IvirkWmY+IjiYdaN1wfQ5OHYk53Oa6EIcsGcfHqTkywhvd3YeFj6VQ3ZlxTmRmq7dJ+zhnluOF4kDbpk3s9u3Yx4H12xiQJt1IGpAMgQMBcilibfymUOCy1w8sqOaI3XUQC89+QgFxWKgpxzZcWEr9pUEZUVzSoedT0wGS5DQ0Zx8F1xbnkE4oEOudx0pA703Qnsx8k5Cn5MbXXAZ1RVWrDyWmyIlpYpEf/h3LwCU6BbkHyDsj4836pC1pTgFb+KIHSO0Dvub8xfW8t4RRc74dPob55KzpLwaTrMIDon/w3MOuQoJNjINJZmI6UHQkWzfAJbZjoRz77r6MLHG1qoIvXVa9il8+5zBLNQeuUbB363276jelHCeuIQVaxCa9k5bdncmWMsH/p9YJHe2r0M/bdKGIvwDL41jU7whrP7yhz4nmdMRBzj9GMx9TZ64y7U4pEkWxmYR3VlSd0NHpAvGTzan0OhfHczFogC8sB5O8O8uAMxCs96f47RFa6eoxSzaEBe8aaAA4sVZ16womgMQODHOON6Si0Fotci119kRuH8SyOdvOU4gNFg940o2j4=
